### ISSUE TITLE
I need your help my brother

### ISSUE THREAD

**Issue by wangminji** [cosmicog/ccrp_omnet4#2]
Thank you very much for your reply, my brother.
And I really need your help. So, I have a few questions to ask you please. 
1. Is the code for this project complete? 2. Can the code run on your computer?
When I was using it, I used the import function in the Omnet++ environment, and then imported the project into the environment, but the result was a lot of errors, such as many functions do not recognize. Is the method I use correct?
Please help me, thank you very much, my brother.

**Comment by cosmicog** [comment]
This project was working well with Ubuntu 14.04 and OMNet++ 4.5. Unfortunately I don't have a computer which has 14.04. But If I would try to use this code in newer version, I would follow these footsteps:
 1.  **Install** Newer Version OMNeT++ on supported Ubuntu version ( Currently Ubuntu 16.04 LTS or 18.04 LTS and OMNeT++ 5.3, Extra information: https://www.omnetpp.org/doc/omnetpp/InstallGuide.pdf ).
 2.  Follow the **tutorials and documanetations** ( https://docs.omnetpp.org and https://www.omnetpp.org/documentation ) and try to write working examples.
 3.  Read the **paper** ( https://doi.org/10.1109/CHINACOM.2008.4685184 ), understand the **algorithm** and inspect my code for seeing how did I make it. 
 4.  Create a **new project** on new version. After that, you can try to write the algorithm better or more clear, or you can copy functions and classes, and fix includes / other things.

I hope it's clear enough.
